remote=['onedrive','gdrive']

[path]
'C:\Users\Initsnow\Pictures'=['Pictures',"gdrive"]
'C:\Users\Initsnow\Documents\windows-dotfiles'=['backups\windows-dotfiles',"onedrive"]
'C:\Users\Initsnow\Documents\books'=['backups\books',"gdrive"]
'C:\Users\Initsnow\Documents\Audio'=['backups\Audio','gdrive']
